"""Initial migration.

Revision ID: 9675c78cdcbb
Revises: 4d680bc72037
Create Date: 2021-12-18 18:58:43.279572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9675c78cdcbb'
down_revision = '4d680bc72037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'about_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('about_test', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
